version: "3.3"
services:
  backup:
    container_name: mysql_backup
    build:
      context: .
    restart: always
    volumes:
      - ./data:/backup:rw
      - ./logs/backup.log:/var/log/backup.log:rw
    environment:
      - MYSQL_DAYS=7
      - CRONTAB_TIME=0 5 * * *
      - MYSQL_HOST=10.28.1.67
      - MYSQL_PORT=3000
      - MYSQL_USER=root
      - MYSQL_PWD=123456
      - MYSQL_DB_NAME=user
